Create Migrations with Relationships
mla-wtag/ml_Journey pull request #1
Opened 2023-08-24 12:19 UTC by mla-wtag

[JTJ-44](https://welltravel.atlassian.net/browse/JTJ-44)

2023-08-24 12:32 UTC, tgi-wtag requested changes

2023-08-24 12:32 UTC, tgi-wtag commented on app/models/journal.rb
> +
please cut out the superfluous spaces or at least follow a consistent pattern(always one line, always two lines).

2023-08-24 12:32 UTC, tgi-wtag commented on app/models/journal.rb
> +
this ofc applyes to all 14 files.

2023-08-24 12:53 UTC, tgi-wtag approved these changes
looks ok to me

2023-08-24 12:58 UTC, meb-wtag commented
All ok!

2023-08-24 12:59 UTC, meb-wtag approved these changes
all ok!

2023-08-30 12:43 UTC, lra-wtag requested changes

2023-08-30 12:43 UTC, lra-wtag commented on db/migrate/20230823111409_create_users.rb
> +end
need formatting

2023-08-30 12:43 UTC, lra-wtag commented on db/migrate/20230823115839_create_journals.rb
> +	def up
need formatting

2023-08-30 12:43 UTC, lra-wtag commented on db/migrate/20230823115839_create_journals.rb
> +end
always add an extra line at the end of the file

2023-08-30 12:43 UTC, lra-wtag commented on db/migrate/20230823124431_create_tasks.rb
> +	def up
need formatting

2023-08-30 12:43 UTC, lra-wtag commented on db/migrate/20230823111409_create_users.rb
> +		create_table :users, id: false do |t|
```suggestion
		create_table :users, do |t|
```

2023-08-30 12:43 UTC, lra-wtag commented on db/migrate/20230823111409_create_users.rb
> +			t.integer :user_id, primary_key: true
in rails these ids get created automatically therefore we do not need these columns

2023-08-30 12:43 UTC, lra-wtag commented on db/migrate/20230823115839_create_journals.rb
> +			t.integer :journal_id, primary_key: true
in rails these ids get created automatically therefore we do not need these columns

2023-08-30 12:43 UTC, lra-wtag commented on db/migrate/20230823115839_create_journals.rb
> +			t.integer :user_id
is this the foreign key ? If so, then please define it as follows
```suggestion
			t.integer :user_id, foreign_key: true
```

2023-08-30 12:43 UTC, lra-wtag commented on db/migrate/20230823124431_create_tasks.rb
> +			t.integer :user_id
is this the foreign key ? If so, then please define it as follows
```suggestion
			t.integer :user_id, foreign_key: true
```

2023-08-30 12:43 UTC, lra-wtag commented on db/migrate/20230823124431_create_tasks.rb
> +			t.integer :task_id, primary_key: true
in rails these ids get created automatically therefore we do not need these columns

2023-08-30 12:43 UTC, lra-wtag commented on db/migrate/20230823124431_create_tasks.rb
> +		create_table :tasks, id: false do |t|
```suggestion
		create_table :tasks do |t|
```

2023-08-30 12:43 UTC, lra-wtag commented on test/fixtures/journals.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
no need of this file. please delete it

2023-08-30 12:43 UTC, lra-wtag commented on test/fixtures/tasks.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
no need of this file. please delete it

2023-08-30 12:43 UTC, lra-wtag commented on test/fixtures/users.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
no need of this file. please delete it

2023-08-30 12:43 UTC, lra-wtag commented on test/models/journal_test.rb
> +require "test_helper"
no need of this file. please delete it

2023-08-30 12:43 UTC, lra-wtag commented on test/models/task_test.rb
> +require "test_helper"
no need of this file. please delete it

2023-08-30 12:43 UTC, lra-wtag commented on test/models/user_test.rb
> +require "test_helper"
no need of this file. please delete it

2023-08-30 12:47 UTC, tgi-wtag commented on db/migrate/20230823111409_create_users.rb
> +			t.string :lastname, limit: 100, nul: false
dont add limits here ( i dont know why, but laila told me so )

2023-08-30 12:47 UTC, tgi-wtag commented on db/migrate/20230823115839_create_journals.rb
> +			t.text :goalstoday
t.text :goals_today
...

2023-08-30 12:47 UTC, tgi-wtag commented on db/migrate/20230823124431_create_tasks.rb
> +			t.string :taskname
task_name

2023-08-30 12:48 UTC, meb-wtag reviewed
Please work on formatting

2023-08-30 12:48 UTC, meb-wtag commented on config/database.yml
>    username: michaellavelanet
Username and Password is not needed, or do you think so?

2023-08-30 12:48 UTC, meb-wtag commented on db/migrate/20230823111409_create_users.rb
> +		create_table :users, id: false do |t|
Formating rules have to be regarded, if not your collegues will be effected.

2023-08-30 14:25 UTC, lra-wtag requested changes

2023-08-30 14:25 UTC, lra-wtag commented on db/migrate/20230823111409_create_users.rb
> +			t.string :designation, limit: 50
no need of this validation in the db but in the model

2023-08-30 14:25 UTC, lra-wtag commented on db/migrate/20230823111409_create_users.rb
> +			t.binary :profile_picture, limit: 10.megabytes
no need of this validation in the db but in the model

2023-08-30 14:25 UTC, lra-wtag commented on db/migrate/20230823124431_create_tasks.rb
> +	    	t.integer :status, limit: 3
no need of this validation in the db but in the model

2023-08-31 07:07 UTC, lra-wtag requested changes

2023-08-31 07:07 UTC, lra-wtag commented on app/controllers/journals_controller.rb
> +end
we need the journal model as well as we have the journal controller and journal table

2023-08-31 07:07 UTC, lra-wtag commented on test/fixtures/journals.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
delete this file please

2023-08-31 07:45 UTC, lra-wtag requested changes

2023-08-31 07:45 UTC, lra-wtag commented on db/migrate/20230823111409_create_users.rb
> +end
wrong indentations

2023-08-31 07:45 UTC, lra-wtag commented on db/migrate/20230823115839_create_journals.rb
> +end
wrong indentations

2023-08-31 07:45 UTC, lra-wtag commented on db/migrate/20230823124431_create_tasks.rb
> +end
wrong indentations

2023-08-31 07:45 UTC, lra-wtag commented on db/schema.rb
> +end
please run the migrations again

2023-08-31 07:45 UTC, lra-wtag commented on db/migrate/20230823115839_create_journals.rb
> +		add_index :journals, :user_id
remove this

2023-08-31 07:45 UTC, lra-wtag commented on db/migrate/20230823124431_create_tasks.rb
> +		add_index :tasks , :user_id
remove this

2023-08-31 12:27 UTC, lra-wtag requested changes

2023-08-31 12:27 UTC, lra-wtag commented on Gemfile
> +gem "pg", "~> 1.2"
no need to add any version
```suggestion
gem "pg"
```

2023-08-31 13:27 UTC, lra-wtag approved these changes

2023-08-31 13:30 UTC, merged

2023-08-31 13:30 UTC, mla-wtag commented
Lettsss goooooooo