#3 JTJ-50-Login-cancancan
mla-wtag/ml_Journey pull request #3
Opened 2023-09-19 09:21 UTC by mla-wtag

[JTJ-50](https://welltravel.atlassian.net/jira/software/projects/JTJ/boards/44?selectedIssue=JTJ-50)

**Description**
- Currently, the roles of users and admins have the same capabilities. However, this code is intended to serve as a blueprint for future modifications.

https://github.com/mla-wtag/ml_Journey/assets/141820916/a1fde023-a0a8-4a56-baca-20c85b361d0a

2023-09-19 10:04 UTC, evk-wtag commented on app/models/ability.rb
> +
For this PR, I think only this should be enough:
```
def initialize(user)
  return unless user

  can :manage, User
end
```

But I do understand you are exploring the ways and keeping it for future references, so you can keep it if you want to for now. But in a future PR, you should use just as much is required for the current story.

2023-09-19 10:09 UTC, evk-wtag commented on app/models/user.rb
> +  enum role: { user: 0, admin: 1 }
Let's move the enum below the has_one relations.

We can follow a file format like:
- has_relations
- enums
- validations
- methods

2023-09-19 10:09 UTC, evk-wtag commented on app/models/user.rb
> +  validates_presence_of :firstname, :lastname, :employee_id, :date_of_birth, :joining_day, :profile_photo, :designation, :role, message: ->(_, _) { I18n.t('validations.presence') }
```suggestion
  validates_presence_of :first_name, :last_name, :employee_id, :date_of_birth, :joining_day, :profile_photo, :designation, :role, message: ->(_, _) { I18n.t('validations.presence') }
```

2023-09-19 10:12 UTC, evk-wtag commented on app/models/user.rb
> +  end
I think this method is not needed. Rails gives you a way to find enums efficiently like, user.admin? or user.user?

Check this: https://api.rubyonrails.org/v5.1/classes/ActiveRecord/Enum.html

2023-09-19 10:21 UTC, evk-wtag commented on spec/.DS_Store
Let's remove this file

2023-09-19 13:34 UTC, lra-wtag requested changes

2023-09-19 13:34 UTC, lra-wtag commented on app/controllers/user_sessions_controller.rb
> +    @user = User.find_by(first_name: params[:user][:first_name])
instead of first_name, isn't it better to do it with the email? Because first name can be same for many people?

2023-09-19 13:34 UTC, lra-wtag commented on db/migrate/20230918145338_alter_users2.rb
> +class AlterUsers2 < ActiveRecord::Migration[7.0]
```suggestion
class AlterUsersTable < ActiveRecord::Migration[7.0]
```

2023-09-20 05:06 UTC, chm-wtag approved these changes

2023-09-20 05:06 UTC, chm-wtag commented on app/models/ability.rb
> +    return unless user
it is a convention to add a new line after guard clause.

2023-09-20 06:15 UTC, lra-wtag requested changes

2023-09-20 06:15 UTC, lra-wtag commented on app/models/user.rb
> +  has_one_attached :profile_photo
maybe you can validate the type of the profile photo such as only allow png, jpeg, jpg files only

2023-09-20 12:48 UTC, lra-wtag approved these changes

2023-09-20 12:53 UTC, merged