all users | authorization | navigation bar
mla-wtag/ml_Journey pull request #7
Opened 2023-10-12 08:06 UTC by mla-wtag

[JTJ-33](https://welltravel.atlassian.net/jira/software/projects/JTJ/boards/44?selectedIssue=JTJ-33)

**Description**
- In this PR, I primarily addressed some link issues beside adding a index view.
- The "task" link in the navigation bar hasn't been implemented yet for this reason there's a temporary link to the root_path.
 

https://github.com/mla-wtag/ml_Journey/assets/141820916/5705d44d-39cf-4e71-b29c-8d5432dba724

2023-10-12 08:37 UTC, chm-wtag approved these changes

2023-10-12 08:37 UTC, chm-wtag commented on app/controllers/user_sessions_controller.rb
> +  include ApplicationHelper
it should work even without this line, could you please try? 🤔

2023-10-12 09:47 UTC, evk-wtag commented on app/controllers/application_controller.rb
> +  end
Let's rearrange it and place it above the current_user method for readability

2023-10-12 09:49 UTC, evk-wtag commented on app/views/users/index.html.erb
> +          <td><%= link_to t('views.profile'), user_path(user) %></td>
```suggestion
        <td><%= link_to t('views.profile'), user_path(user) %></td>
```

2023-10-12 09:49 UTC, evk-wtag commented on app/views/users/index.html.erb
> +        <br>
```suggestion
        <br>
        <td><%= link_to t('views.profile'), user_path(user) %></td>
        <br>
```

2023-10-12 09:49 UTC, evk-wtag commented on spec/controllers/users_controller_spec.rb
> +      let(:user) { FactoryBot.create(:user, role: 'admin_role') }
```suggestion
      let(:user) { FactoryBot.create(:user, role: :admin_role) }
```

2023-10-12 09:50 UTC, evk-wtag commented on spec/controllers/users_controller_spec.rb
> +      let(:user) { FactoryBot.create(:user, role: 'user_role') }
```suggestion
      let(:user) { FactoryBot.create(:user, role: :user_role) }
```

2023-10-12 09:51 UTC, evk-wtag approved these changes

2023-10-12 10:16 UTC, mla-wtag commented on app/controllers/user_sessions_controller.rb
> +  include ApplicationHelper
I removed it from users_controller.rb and user_sessions_controller.rb, but added the line to application_controller.rb

2023-10-15 03:33 UTC, lra-wtag requested changes

2023-10-15 03:33 UTC, lra-wtag commented on app/views/layouts/_navbar.html.erb
> +  <title>Document</title>
i18n please

2023-10-16 06:09 UTC, lra-wtag approved these changes

2023-10-16 06:12 UTC, merged